---


- name: Install iterm2-beta
  homebrew_cask:
    name: iterm2-beta
  tags:
    - apps
    - iterm

- name: Copy iterm settings
  copy:
    src: com.googlecode.iterm2.plist
    dest: ~/Library/Preferences/com.googlecode.iterm2.plist
  tags:
    - apps
    - iterm

- name: Reload iterm settings
  shell: defaults read com.googlecode.iterm2
  tags:
    - apps
    - iterm

- name: Open iterm
  shell: open -a /Applications/iTerm.app
  changed_when: false
  tags:
    - apps
    - iterm

